export { SidebarButton } from "./SidebarButton";
export { InicioContent } from "./InicioContent";
export { AgendaContent } from "./AgendaContent";
export { DisponibilidadContent } from "./DisponibilidadContent";
export { ConsultasContent } from "./ConsultasContent";
export { RecetasContent } from "./RecetasContent";
export { EstudiosContent } from "./EstudiosContent";
export { CirugiasContent } from "./CirugiasContent";
export { HistorialClinicoModal } from "./HistorialClinicoModal";
